### ISSUE TITLE
CYK algorithm works badly.

### ISSUE THREAD

**Issue by iasx** [syntpump/syntext-py-ua#30]
CYK algorithm is unable to build a syntax tree of a sentence with 4 or more words.
https://github.com/syntpump/syntext-py-ua/blob/1d4bdc00731f068a05f4e9afa09ed0cc23a515e4/pysyntext/libs/cykalgo.py#L81-L87

**Comment by lynnporu** [comment]
Oh, what a shame. I suppose, the problem appeared after refactoring, because it works just fine at [this moment](https://github.com/syntpump/syntext-py-ua/blob/b33cdf0cd92ce53cacdfcc0af3e94bc5de6e1cf1/pysyntext/cykalgo.py).
